# Server
server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}

# JWT
app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiry=60000
app.jwt.refresh-token-expiry=604800000

# Mail
app.mail.enabled=${APP_MAIL_ENABLED:false}
spring.mail.host=${SPRING_MAIL_HOST:}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=15000

# Async
app.async.core-pool-size=5
app.async.max-pool-size=10
app.async.queue-capacity=100

spring.application.name=IT-Ticket-Resolution-System

app.base-url=${BASE_URL}

logging.level.com.itticket=DEBUG
logging.level.org.springframework.security=INFO